### PR TITLE
Sets 'variables_input_name' to the right value

### PR DESCRIPTION
**Pull request by n1ru4l**
graphiql and all clients I have used use 'variables' as the identifier.

### CODE REVIEW

**Comment by n1ru4l** [comment]
I fixed the test!

**Comment by n1ru4l** [comment]
On some php version the test fails with a timeout...

**Comment by dmongeau** [comment]
Not sure why this pull request. The test are passing on both master and develop branch

**Comment by n1ru4l** [comment]
Any way to restart the tests? They are all passing on my machine :sweat_smile:

**Comment by dmongeau** [comment]
I have made the changes in v1.0.14

**Pull request closed without merging**
