### PR TITLE
Added pagination type

### PR DESCRIPTION
**Pull request by kevinvdburgt**
This should make pagination a bit easier, instead of creating a pagination type for each other type (#187) now simply use this in your Query:

```php
<?php

namespace App\GraphQL\Query;

use Folklore\GraphQL\Support\Query;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;
use GraphQL;

use App\Models\User;

class UsersQuery extends Query
{
    protected $attributes = [
        'name' => 'UsersQuery',
        'description' => 'A query'
    ];

    public function type()
    {
        return GraphQL::paginate('User');
    }

    public function args()
    {
        return [
            'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'description' => 'Display a specific page',
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'description' => 'Limit the items per page',
            ],
        ];
    }

    public function resolve($root, $args, $context, ResolveInfo $info)
    {
        return User::paginate($args['limit'] ?? 20, ['*'], 'page', $args['page'] ?? 0);
    }
}

```

---

Example:

Query:
```graphql
{
    users(page:1 limit:10) {
        data {
            id
        }
        total
        limit
        page
    }
}
```

results in:

```json
{
    "data": {
        "users": {
            "data": [
                {
                    "id": "89734"
                },
                {
                    "id": "89735"
                },
                {
                    "id": "99009"
                },
                {
                    "id": "99010"
                },
                {
                    "id": "104032"
                },
                {
                    "id": "104033"
                },
                {
                    "id": "104034"
                },
                {
                    "id": "104035"
                },
                {
                    "id": "104036"
                },
                {
                    "id": "104037"
                }
            ],
            "total": 22,
            "limit": 10,
            "page": 1
        }
    }
}
```

### CODE REVIEW

**Comment by dmongeau** [comment]
Seems like there is a bug in the paginate method. The `$name` variable is never declared

**Comment by kevinvdburgt** [comment]
@dmongeau Whoops, let me fix that, dont know what happend before i submitted the MR :/

**Comment by kevinvdburgt** [comment]
@dmongeau fixed the issue, can you check the PR again?

**Comment by kevinvdburgt** [comment]
@crissi what do you mean?

**Comment by crissi** [comment]
image

from the laravel docs: https://laravel.com/docs/5.0/pagination

So If we instead could resolve only the query:

```
public function resolve($root, $args, $context, ResolveInfo $info)
{
      return User::query();
}

```
I don't know the best way to add the  limit and page argument here....

We would be able to make less calls to the database, since the simplePaginate do not check the count of the table...

**Comment by kevinvdburgt** [comment]
For simple pagination you can use the default type (without pagination `return GraphQL::paginate('User');` and by using just `return GraphQL::type('User');`) because you should already know on which page you are.

```graphql
query {
  users(page:1 limit:10) {
    id
  }
}
```

**Comment by alrik11es** [comment]
While this is waiting to be merged I've managed to surpass this limitation with the code provided by @kevinvdburgt 

I've added this class to my project.
```php
<?php

namespace App\GraphQL\Type;

use GraphQL\Type\Definition\Type;
use GraphQL\Type\Definition\ObjectType;
use Illuminate\Pagination\LengthAwarePaginator;

class PaginationType extends ObjectType
{
    /**
     * PaginationType constructor.
     * @param String $typeName
     */
    public function __construct($typeName)
    {
        parent::__construct([
            'name' => $typeName . 'Pagination',
            'fields' => [
                'data' => [
                    'type' => Type::listOf(\GraphQL::type($typeName)),
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->getCollection();
                    },
                ],
                'total' => [
                    'type' => Type::nonNull(Type::int()),
                    'description' => 'Number of total items selected by the query',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->total();
                    },
                    'selectable' => false,
                ],
                'limit' => [
                    'type' => Type::nonNull(Type::int()),
                    'description' => 'Number of items returned per page',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->perPage();
                    },
                    'selectable' => false,
                ],
                'page' => [
                    'type' => Type::nonNull(Type::int()),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->currentPage();
                    },
                    'selectable' => false,
                ],
            ],
        ]);
    }
}
```
Now you must call that class like this:

```php
    public function type()
    {
        return new PaginationType('Purchase');
    }
```
Don't forget to add the pagination arguments.

```php
'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'description' => 'Display a specific page',
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'description' => 'Limit the items per page',
            ],
```
```php
$query->paginate($args['limit'] ?? 20, ['*'], 'page', $args['page'] ?? 0);
```
So this is all, and it will work. Also it gives me ideas on how to treat other data.

Note: Seems ready to merge.

**Comment by faiverson** [comment]
Can I append some new fields like Laravel pagination?
```
<?php

namespace Folklore\GraphQL\Support;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type as GraphQLType;
use Illuminate\Pagination\LengthAwarePaginator;
use GraphQL;

class PaginationType extends ObjectType
{
    public function __construct($typeName)
    {
        parent::__construct([
            'name'  => $typeName . 'Pagination',
            'fields' => [
                'items' => [
                    'type' => GraphQLType::listOf(GraphQL::type($typeName)),
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->getCollection();
                    },
                ],
                'total' => [
                    'type' => GraphQLType::nonNull(GraphQLType::int()),
                    'description' => 'Number of total items selected by the query',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->total();
                    }
                ],
                'per_page' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Number of items returned per page',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->perPage();
                    }
                ],
                'last_page' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->lastPage();
                    }
                ],
                'current_page' => [
                    'type' => GraphQLType::nonNull(GraphQLType::int()),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->currentPage();
                    }
                ],
                'from' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->firstItem();
                    }
                ],
                'to' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->lastItem();
                    }
                ],
                'next_page_url' => [
                    'type' => GraphQLType::string(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->nextPageUrl();
                    }
                ],
                'prev_page_url' => [
                    'type' => GraphQLType::string(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function ($data) {
                        return $data->previousPageUrl();
                    }
                ],
            ],
        ]);
    }
}
```

**Comment by faiverson** [comment]
Also, I was wondering if there's a better way to set page and limit/count in the queries. I feel that I'm repeating the code all the time.
Any ideas?

**Comment by alrik11es** [comment]
@faiverson The only way I know for sure it will work is to create an extendable base class for the query. So in the child classes you should add args to the parent args() method array instead of creating new array.

```php
<?php
namespace App\GraphQL\Query;

use Folklore\GraphQL\Support\Query;
use GraphQL\Type\Definition\Type;

class BaseQuery extends Query
{
    public function args()
    {
        return [
            'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'description' => 'Display a specific page',
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'description' => 'Limit the items per page',
            ],
        ];
    }
}
```

```php
    public function args()
    {
        return array_merge(parent::args(), [
            'productId' => ['name' => 'productId', 'type' => Type::int()],
            'dateStart' => ['name' => 'dateStart', 'type' => Type::string()],
            'dateEnd' => ['name' => 'dateEnd', 'type' => Type::string()],
        ]);
    }
```
Any other idea?

Side-question: Do you know any way to pass an object like result of the resolve in the PaginationType class?

**Comment by faiverson** [comment]
I was thinking something like an interface Pagination... 

Could you tell me why you need the response into PaginationType? It doesn't seem to be the right way.
resolve would be executed after the PaginationType, that's why you are doing things like:
`'resolve' => function (LengthAwarePaginator $data) {
                        return $data->firstItem();
                    }`

**Comment by alrik11es** [comment]
I think the problem is that the library has restricted constraints with the types you need to use. In fact if the library were more open without that much casting would be even more polyvalent. That's why he uses this horrific way to do it.

**Comment by codeitlikemiley** [comment]
GraphQL::paginate('User') , 
im getting this 
PHP Error:  Call to undefined method Folklore\GraphQL\GraphQL::paginate()

Im Using Lumen and Moloquent ... Dont know what is the problem, 
can someone confirm that GraphQL::paginate method exists?

**Comment by kevinvdburgt** [comment]
@codeitlikemiley The `paginate` method doesn't exists yet, that is where this PR is for :)

**Comment by codeitlikemiley** [comment]
i think its better if this can be encapsulated in a meta field...


```json
meta: {
   "total": 50,
   "per_page": 15,
   "current_page": 1,
   "last_page": 4,
   "first_page_url": "http://laravel.app?page=1",
   "last_page_url": "http://laravel.app?page=4",
   "next_page_url": "http://laravel.app?page=2",
   "prev_page_url": null,
   "path": "http://laravel.app",
   "from": 1,
   "to": 15,
}
```

**Comment by dmongeau** [comment]
Yes, I'll definitely go with a PaginationType that encapsulate only the pagination fields. The final structure should be something like this, in my opinion:

```
query UsersPaginated {
    items { // Type::listOf(GraphQL::type('User'))
        id
        // etc...
    }
    pagination { // GraphQL::type('Pagination')
        total
        per_page
        // etc...
    }
}
```

**Comment by rpopuc** [comment]
I liked the idea of "meta field". So I coded a `PaginationMetaType` class:

```php

namespace Folklore\GraphQL\Support;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type as GraphQLType;
use Illuminate\Pagination\LengthAwarePaginator;
use GraphQL;

class PaginationMetaType extends ObjectType
{
    public function __construct()
    {
        parent::__construct([
            'name'  => 'Meta',
            'fields' => [
               'total' => [
                    'type' => GraphQLType::nonNull(GraphQLType::int()),
                    'description' => 'Number of total items selected by the query',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->total();
                    },
                ],
                'limit' => [
                    'type' => GraphQLType::nonNull(GraphQLType::int()),
                    'description' => 'Number of items returned per page',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return (int)$data->perPage();
                    },
                ],
                'page' => [
                    'type' => GraphQLType::nonNull(GraphQLType::int()),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->currentPage();
                    },
                ],
                'last_page' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->lastPage();
                    },
                ],
                'from' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->firstItem();
                    },
                ],
                'to' => [
                    'type' => GraphQLType::int(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->lastItem();
                    },
                ],
                'next_page_url' => [
                    'type' => GraphQLType::string(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->nextPageUrl();
                    }
                ],
                'prev_page_url' => [
                    'type' => GraphQLType::string(),
                    'description' => 'Current page of the cursor',
                    'resolve' => function ($data) {
                        return $data->previousPageUrl();
                    }
                ],
            ],
        ]);
    }
}
```

And I changed the class `PaginationType`to use it:

```php

<?php

namespace Folklore\GraphQL\Support;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type as GraphQLType;
use Illuminate\Pagination\LengthAwarePaginator;
use GraphQL;

class PaginationType extends ObjectType
{
    public function __construct($typeName)
    {
        parent::__construct([
            'name'  => $typeName . 'Pagination',
            'fields' => [
                'data' => [
                    'type' => GraphQLType::listOf(GraphQL::type($typeName)),
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->getCollection();
                    },
                ],
                'meta' => [
                    'type' => new PaginationMetaType,
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data;
                    },
                ],
            ],
        ]);
    }
}
```

And as I also liked the idea of a "base query class", I wrote a class `PaginationQuery`:

```php

<?php

namespace Folklore\GraphQL\Support;

use GraphQL;
use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\Query;

class PaginationQuery extends Query
{

    public function type()
    {
        return new PaginationType($this->getType());
    }

    public function args()
    {
        return array_merge( $this->getArgs(), [
            'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'description' => 'Display a specific page',
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'description' => 'Limit the items per page',
            ],
        ]);
    }

    public function resolve($root, $args)
    {
        $query = $this->getQuery($args);
        if ( $query ) {
            return $query->paginate($args['limit'] ?? 0, ['*'], 'page', $args['page'] ?? 0);
        }
        return null;
    }

    protected function getArgs()
    {
        return [];
    }

    protected function getQuery($args)
    {
        return null;
    }

}
```

Which can be used as follows:

```php

<?php

namespace App\GraphQL\Query;

use GraphQL;
use GraphQL\Type\Definition\Type;
use Folklore\GraphQL\Support\PaginationQuery;
use App\User;

class UsersQuery extends PaginationQuery
{
    protected $attributes = [
        'name' => 'users'
    ];

    protected function getType()
    {
        return 'User';
    }

    protected function getArgs()
    {
        return [
            'id' => ['name' => 'id', 'type' => Type::int()],
            'email' => ['name' => 'email', 'type' => Type::string()],
            'page' => [
                'name' => 'page',
                'type' => Type::int(),
                'description' => 'Display a specific page',
            ],
            'limit' => [
                'name' => 'limit',
                'type' => Type::int(),
                'description' => 'Limit the items per page',
            ],
        ];
    }

    protected function getQuery($args)
    {
        $query = User::query();
        if (isset($args['id'])) {
            $query->where('id' , $args['id'])->get();
        } else if(isset($args['email'])) {
            $query->where('email', $args['email'])->get();
        }
        return $query;
    }
}
```

And this class responds very well to the following query, for example:

```
{
  users(limit: 10, page: 1) {
    data {
      id
      email
      name
    }
    meta {
      total,
      page,
      last_page
    }
  }
}
```

I believe all this code needs polishing, but for my tests, it worked very well.

What do you think?

**Comment by faiverson** [comment]
I'd add the ability to change the words
`
meta {
      total,
      page,
      last_page
    }
`
Maybe I need to use:
`pagination {
      total,
      page,
      lastPage
    }
`
Maybe if we can change the args in the setting or something like that (optional) would be nice

**Comment by rpopuc** [comment]
Something like?:

```php
<?php

namespace Folklore\GraphQL\Support;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type as GraphQLType;
use Illuminate\Pagination\LengthAwarePaginator;
use GraphQL;

class PaginationType extends ObjectType
{
    public function __construct($typeName, $metaFieldName = 'meta' )
    {
        parent::__construct([
            'name'  => $typeName . 'Pagination',
            'fields' => [
                'data' => [
                    'type' => GraphQLType::listOf(GraphQL::type($typeName)),
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data->getCollection();
                    },
                ],
                $metaFieldName => [
                    'type' => new PaginationMetaType,
                    'resolve' => function (LengthAwarePaginator $data) {
                        return $data;
                    },
                ],
            ],
        ]);
    }
}
```

**Comment by faiverson** [comment]
```
$metaFieldName = config('graphql.pagination.metafield');
```
Might be the same for properties in PaginationMetaType

**Comment by hobord** [comment]
http://graphql.org/learn/pagination/

**Comment by faistoiplaisir** [comment]
@rpopuc Your code seems not functionnal when you use your PaginationMetaType in at least 2 differents query. GraphQL Shema can't contains 2 types names "Meta" (with X differents query, you create X instances of PaginationMetaType).

Instead of creating a new PaginationMetaType, you can have a TypeRegistry to instanciate only one type. I had that error with your code, and the exception message I received gave me that url to visit: http://webonyx.github.io/graphql-php/type-system/#type-registry. Implementing it was quick and solve that problem.

(The problem doesn't appear with PaginationType because you already add a $typename in front of its 'name').

Now, I've another question about pagination. I'm totally new with GraphQL, maybe my question is stupid, or I missunderstood something, but that documention: http://graphql.org/learn/pagination/ talk about connection/edges/node/cursor. And I also saw a branch called feature/relay that seems very close to that concept ... I mean, pagination/connection/cursor (https://github.com/Folkloreatelier/laravel-graphql/blob/feature/relay/docs/relay.md) ...

So, I'm not sure on what is exactly Relay, but If I'm not wrong, the "real" solution seems to be in that branch. No ? I'm wrong ?

**Comment by kikoseijo** [comment]
My recommendation its start with it pure, as its using relay for the client, and yes, does it all for you.,
Haven't tested the normal branch, I suppose its for Apollo and other client wrappers around GraphQL.

I have published a Lumen + Relay for server and a React+Relay client app if you want some working examples.

Welcome to GraphQL, once you try it you can't live without it.

**Pull request closed without merging**
