### PR TITLE
Feature/relay minor fixes

### PR DESCRIPTION
**Pull request by 4levels**

### CODE REVIEW

**Comment by 4levels** [comment]
Hi @dmongeau,

I'm still investigating the build erros..
I got fatal errors when running the GraphiQL web interface, complaining that the route "graphql.query" doesn't exist.
In your routes.php file you defined the routes (foreach method) as "graphq.$method.query"

**Comment by 4levels** [comment]
Hi David,

I can fix the tests locally by using updated versions of "orchestra/testbench": "3.4.*" & "illuminate/support": "5.4.*" and by removing the change to the GraphiQLComposer class in this PR.  This marks all tests as successfull, but brings back the "undefined route graphql.query" error in the UI

By adding a fallback route in routes.php I can get around this, and even undo the change in View/GraphiQLComposer.  I'll update the PR.

I also updated the ServiceProviderTest to use the new uri() instead of getUri() on the router.

**Comment by 4levels** [comment]
Hmm, the failing tests seem related to the way phpunit is called in Travis:
when using vendor/bin/phpunit all goes well, when using the (global) phpunit call, it uses the Travis version of phpunit, causing this error.

Is there a way to tell Travis to use vendor/bin/phpunit or alternatively update phpunit in Travis?

**Comment by dmongeau** [comment]
I've fixed the issue with phpunit and travis!

**Pull request merged**
