### PR TITLE
Add a command to generate a GraphiQL view and a route at /graphiql

### PR DESCRIPTION
**Pull request by pelletiermaxime**
For me GraphiQL is one of the best features of GraphQL, so I tought I would share a command to automatically create a blade view and add a /graphiql route to your web.php route file.
I used a CDN for all assets to have no added dependencies to the project.

Thanks!

### CODE REVIEW

**Comment by nwalke** [comment]
Just a note that this does not work with Lumen

**Comment by pelletiermaxime** [comment]
Ah, right. The whole command wouldn't work anyway because iirc Lumen doesn't even have views, right ?
If that's the case we could just not register the command in Lumen.

**Comment by dmongeau** [comment]
I'll merge it on develop, just to test it out a bit and also create unit test for it.

**Comment by dmongeau** [comment]
I've done a couple of modifications on the way it works. It is on the develop branch. Basically I've removed the need to use an Artisan command as views and routes are already supported by packages. So no need to use generator for that. Also, it should work with Lumen.

**Comment by nwalke** [comment]
You guys are awesome!  Thanks!

**Comment by dmongeau** [comment]
If you have any chance to test it, and have any feedback. That would be nice. I will merge it on master soon.

**Comment by nwalke** [comment]
I can see that it added the route `/graphiql` but when I go there I'm getting:
```
InvalidArgumentException in FileViewFinder.php line 112: No hint path defined for [graphql].
```

**Comment by pelletiermaxime** [comment]
I did it as a command so that users could easily customize the route and the look of graphiql, but your way seems simpler and you added config options for everything, so nice job!

**Comment by sandervanhooft** [comment]
Having a working GraphiQL merged into this package would be awesome!

**Comment by dmongeau** [comment]
GraphiQL support has been merged to master. Check version 1.0.5

**Comment by dmongeau** [comment]
@nwalke Should be fixed in 1.0.6

**Comment by nwalke** [comment]
I've got it working now!  Thanks!

**Comment by sandervanhooft** [comment]
@dmongeau , @nwalke How can I start using this awesomeness?

I've been working with GraphiQL using the Apollo Stack, which is very cool if you're using an Express setup. For my Laravel projects, I'll be giving this package a try. GraphiQL is a dealbreaker - dealmaker in this case :).

**Comment by nwalke** [comment]
Make sure you're on 1.0.6 and it adds a graphiql route.

**Comment by sandervanhooft** [comment]
Great, I'll give it a try. Should include this in the readme!

**Comment by sandervanhooft** [comment]
FYI, Had some issues, see #65 .

**Pull request merged**
