### PR TITLE
Allow subscription types to be added

### PR DESCRIPTION
**Pull request by petecoop**

### CODE REVIEW

**Comment by petecoop** [comment]
Have rebased this

**Comment by dmongeau** [comment]
Sorry about the delay, do you mind submitting the pull request to feature/relay branch? Since it's the next release

**Comment by petecoop** [comment]
Hey, I've changed the target. Looks like the feature/relay branch needs a rebase first

**Comment by dmongeau** [comment]
Okay, maybe I can merge it in master and then rebase when I will release feature/relay

**Comment by petecoop** [comment]
I've changed the target back to master... not sure if that's something you can change anyway?

**Comment by codeitlikemiley** [comment]
Is there an example  how to use subscription?

**Comment by cdeeming** [comment]
@codeitlikemiley Hi, did you manage to get subscriptions working with this laravel?

**Pull request merged**
