### PR TITLE
Added middleware option

### PR DESCRIPTION
**Pull request by chiedojohn**
A feature I need so I imagine others will also!

### CODE REVIEW

**Comment by chiedojohn** [comment]
Any update on this?

**Comment by dmongeau** [comment]
To make it backward compatible, I think, you should handle the case where `config('graphql.middleware')` is null (in case it is not present in the `config/graphql.php` file) by providing a default value `config('graphql.middleware', [])`. I will merge it after this change

**Comment by chiedojohn** [comment]
Good call! Just updated.

**Comment by dmongeau** [comment]
Thanks! merged

**Comment by chiedojohn** [comment]
Thank You :)

**Pull request merged**
