### PR TITLE
Update to latest GraphQL, adding support for variables and operationName

### PR DESCRIPTION
**Pull request by rpeterson**

### CODE REVIEW

**Comment by dmongeau** [comment]
Thanks, the v1 branch should includes all this. I will release it as 1.0.0 this week. You can check it out, let me know if anything is missing!

**Comment by mxmtsk** [comment]
@dmongeau the v1 branch does not include the variables part which I think is pretty important since a lot of other libraries are working with it, are you planing on integrating it or would you accept another PR?

**Comment by dmongeau** [comment]
Ok sorry about that, I will add it!

**Comment by dmongeau** [comment]
Actually, I'm confused, it's already there, look at $params.

**Comment by mxmtsk** [comment]
@dmongeau I saw it too, that's why I deleted my comment, sorry! The issue for me is that a lot of libraries I use (for example Apollo Stack for ReactJS) are sending variables as a parameter that is called variables. I don't know if there is an official standard for graphql but it seems that a lot of those libraries use "variables" as the parameter name. Maybe introduce a config item where you can define the parameter name so it is backwards compatible but also more flexible

**Comment by dmongeau** [comment]
Oh! yes, there was an older pull request about that. I will add this as a config option and will made it default in the next major release. I don't know where the params name come from, probably an old habit on my side and since there was not much about GraphQL when I first made this package, it didn't seems a problem back then.

**Comment by dmongeau** [comment]
@mxmtsk It's in 1.0.2

**Comment by mxmtsk** [comment]
@dmongeau awesome thanks

**Pull request closed without merging**
